// <auto-generated />
using System;
using Eri.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eri.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200130044156_Eri")]
    partial class Eri
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Eri.Models.Mst_Available", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Del_Flag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mst_Available");
                });

            modelBuilder.Entity("Eri.Models.Mst_Fixed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Del_Flag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fixed_Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mst_Fixed");
                });

            modelBuilder.Entity("Eri.Models.Mst_Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Income_Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mst_Income");
                });

            modelBuilder.Entity("Eri.Models.Mst_Spend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Spend_Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mst_Spend");
                });

            modelBuilder.Entity("Eri.Models.Mst_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("BLOB");

                    b.Property<string>("User_Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mst_User");
                });

            modelBuilder.Entity("Eri.Models.Tra_Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Income_Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Linked_Flag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Payment_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("User_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tra_Income");
                });

            modelBuilder.Entity("Eri.Models.Tra_Spending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Linked_Flag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Purchase_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Spend_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tra_Spending");
                });
#pragma warning restore 612, 618
        }
    }
}
